services:
  - type: web
    name: QNABot
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: model
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        sync: false  

  - type: worker
    name: QNABot-Worker
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_worker.celery worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: model
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        sync: false 

databases:
  - name: model
    region: oregon
