services:
  - type: web
    name: QNABot
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: model
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: model
    region: oregon
